theme = 'hugo-theme-console'
defaultContentLanguage = 'en'

enableGitInfo = true

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[languages]
  [languages.en]
    title = "Yi's Notepad"
    weight = 1
    languageCode = 'en-us'
    [languages.en.menu]

  [languages.zh-cn]
    title = 'Yi 的记事本'
    weight = 2
    languageCode = 'zh_CN'
    [languages.zh-cn.menu]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animate__animated animate__fadeIn animate__fast" 

[[params.navlinks]]
name = "posts/"
url = "/posts/"

[[params.navlinks]]
name = "about/"
url = "/about/"

[[languages.zh-cn.params.navlinks]]
name = "文章/"
url = "/zh-cn/posts/"

[[languages.zh-cn.params.navlinks]]
name = "关于我/"
url = "/zh-cn/about/"

[[languages.zh-cn.params.navlinks]]
name = "书单/"
url = "/zh-cn/reading-list/"

[[languages.zh-cn.menu.main]]
      name = 'EN/'
      url = '/'
      weight = 1

[[languages.en.menu.main]]
      name = 'zh/'
      url = '/zh-cn'
      weight = 2
